# Generated by Django 5.1.1 on 2024-09-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
