# Generated by Django 4.2.14 on 2024-09-28 14:29

from django.db import migrations, models

def insert_initial_data(apps, schema_editor):
    # Get the model you want to insert data into
    MyModel = apps.get_model('meetings', 'Category')

    # Insert data
    MyModel.objects.create(id=1, name='Koszykówka')    # Basketball
    MyModel.objects.create(id=2, name='Piłka nożna')   # Football (Soccer)
    MyModel.objects.create(id=3, name='Siatkówka')     # Volleyball
    MyModel.objects.create(id=4, name='Tenis')         # Tennis
    MyModel.objects.create(id=5, name='Lekkoatletyka') # Athletics
    MyModel.objects.create(id=6, name='Hokej')         # Hockey
    MyModel.objects.create(id=7, name='Pływanie')      # Swimming
    MyModel.objects.create(id=8, name='Golf')          # Golf
    MyModel.objects.create(id=9, name='Szermierka')    # Fencing
    MyModel.objects.create(id=10, name='Boks')         # Boxing
    MyModel.objects.create(id=11, name='Rugby')        # Rugby

    MeetingModel = apps.get_model('meetings', 'Meeting')
    # Create mock meetings
    meeting1 = MeetingModel.objects.create(
        title="Turniej Koszykówki 2024",
        description="Ogólnopolski turniej koszykówki młodzieżowej.",
        date="2024-05-15 10:00:00",
        location=None,  # Nullable, assume location is not set
    )
    meeting1.categories.add(1)

    meeting2 = MeetingModel.objects.create(
        title="Mistrzostwa Piłki Nożnej",
        description="Mistrzostwa krajowe w piłce nożnej.",
        date="2024-06-20 15:00:00",
        location=None,
    )
    meeting2.categories.add(2)

    meeting3 = MeetingModel.objects.create(
        title="Zawody Siatkówki",
        description="Zawody siatkówki plażowej.",
        date="2024-07-10 09:00:00",
        location=None,
    )
    meeting3.categories.add(3)

    meeting4 = MeetingModel.objects.create(
        title="Turniej Tenisa",
        description="Turniej tenisa amatorskiego.",
        date="2024-08-25 13:00:00",
        location=None,
    )
    meeting4.categories.add(4)

    meeting5 = MeetingModel.objects.create(
        title="Lekkoatletyczne Mistrzostwa",
        description="Mistrzostwa w lekkoatletyce dla dzieci.",
        date="2024-09-05 10:00:00",
        location=None,
    )
    meeting5.categories.add(5)



class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_location_google_url'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data),
    ]
