# Generated by Django 5.1.1 on 2024-09-28 22:05

from django.db import migrations,models

def insert_data(apps, schema_editor):
    ChallengeTemplate = apps.get_model('challenges', "ChallengeTemplate")
    Categories = apps.get_model('meetings', 'Category')
    template = ChallengeTemplate.objects.create(
        lat=50.049683,
        long=19.944544,
        rarity=1,
        type=Categories.objects.all()[0]
    )

    Challenge = apps.get_model('challenges', "Challenge")

    Challenge.objects.create(
        template = template,
        created_at = "2024-09-29 00:15:00",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
